cc_library(
    name = "ImageProcessor",
    srcs = ["ImageProcessor.cpp"],
    hdrs = ["ImageProcessor.hpp"],
    deps = [
        "@lib_CV//:opencv",
        "@lib_TORCH//:libtorch",
    ],
    visibility=["//visibility:public"]
)