cc_library(
    name = "AbstractPostProcessor",
    hdrs = ["Abstract.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//LTPG/Utils:Convert",
        "@lib_TORCH//:libtorch",
    ],
)
