cc_library(
    name = "File",
    srcs = [],
    hdrs = ["File.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Convert",
    srcs = [],
    hdrs = ["Convert.hpp"],
    visibility = ["//visibility:public"],
)
