cc_library(
    name = "File",
    srcs = [],
    hdrs = ["File.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Convert",
    srcs = [],
    hdrs = ["Convert.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "DataTypes",
    srcs = [],
    hdrs = ["DataTypes.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Logger",
    srcs = [],
    hdrs = ["Logger.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//LTPG/Utils:DataTypes",
        "@lib_SPDLOG//:spdlog",
    ],
)
