cc_library(
    name = "Classifier",
    srcs = ["Classifier.cpp"],
    hdrs = ["Classifier.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//LTPG/Utils:DataTypes",
        "@lib_TORCH//:libtorch",
    ],
)
