cc_library(
    name = "Detector",
    srcs = ["Detector.cpp"],
    hdrs = ["Detector.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@lib_CV//:opencv",
        "@lib_TORCH//:libtorch",
    ],
)
